#ifndef _ADAPTIVE_MUTEX_METRIC_H
#define _ADAPTIVE_MUTEX_METRIC_H

#include "pthread_mutex_custom_metric.h"

typedef pthread_mutex_metric_t_c adaptive_mutex_metric_t;

int adaptive_mutex_lock_metric(pthread_mutex_metric_t_c *lock);
#define adaptive_mutex_unlock_metric pthread_mutex_unlock_metric_c
#define adaptive_mutex_init_metric pthread_mutex_init_metric_c

#endif
